version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  nestjs:
    build: ./nest-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://root:password@mongo:27017/
      JWT_SECRET: secret
    volumes:
      - ./nest-backend:/app
      - ./nest-backend/node_modules:/app/node_modules
    depends_on:
      - mongo

  nextjs:
    build:
      context: ./next-frontend
      target: runner
      args:
        - INSTALL_TAILWIND=true
    volumes:
      - ./next-frontend:/app
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      BACKEND_URL: http://nestjs:3000/api
    depends_on:
      - nestjs

volumes:
  mongo-data: