// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./components/layoutWrapper";
// import authenticate from '../../middleware/auth';
// import { useLayoutEffect } from 'react';
// import { redirect } from 'next/navigation';
import { StateProvider } from './StateContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StateProvider>
          <LayoutWrapper>
            {children}  
          </LayoutWrapper>
        </StateProvider>
      </body>
    </html>
  );
}
